### ISSUE TITLE
Emoji not displaying properly on iDevices

### ISSUE THREAD

**Issue by nico29** [BenoitZugmeyer/react-suspense-demo#1]
The content of the `content` rule is displaying a square box 😅
![sans titre](https://user-images.githubusercontent.com/3858041/36963612-3f54e74e-2054-11e8-992b-663b8f3b7a9f.png)

Well done for the implementation ✌

**Comment by BenoitZugmeyer** [comment]
I don't have the issue, it might be an issue with your default sans-serif font. It should display this character: https://www.fileformat.info/info/unicode/char/1f872/index.htm
PR welcome :)

**Comment by BenoitZugmeyer** [comment]
Seems to be broken on Android too. Let's change the arrow to something like https://www.fileformat.info/info/unicode/char/279c/index.htm (no, you won't add an emoji here :smile: )
